import Head from "next/head";
import Sidebar from "../components/common/Sidebar/Sidebar";
import Navbar from "../components/common/Navbar/Navbar";
import MyFiles from "../components/MyFiles";
import { useGetDirectoryQuery } from "../store/api";
import { useRouter } from "next/router";
import { useAppSelector } from "../store/hooks";
import { authSelector } from "../store/authSlice";
import { useEffect } from "react";
import SignIn from "./auth/signin";

export default function Home() {
  const router = useRouter();
  const { isAuthenticated } = useAppSelector(authSelector);
  if (!isAuthenticated && router.pathname !== "/auth/signin") {
    return <SignIn />;
  }

  return (
    <>
      <Head>
        <title>Sam's Drive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-slate-100">
        <Sidebar />
        <section className="flex-1">
          {/* create a simple nav */}
          <Navbar />
          <MyFiles />
        </section>
      </main>
    </>
  );
}
