import Head from "next/head";
import { Inter } from "@next/font/google";
import SidebarLinks from "../components/SidebarLinks";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import MyFiles from "../components/MyFiles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sam's Drive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-slate-100">
        <Sidebar />
        <section className="flex-1">
          {/* create a simple nav */}
          <Navbar />
          <MyFiles />
        </section>
      </main>
    </>
  );
}
